spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          perdicates:
            - Path=/api/v1/customers/**
        - id: customer
          uri: lb://FRAUD
          perdicates:
            - Path=/api/v1/fraud-check/**
        - id: customer
          uri: lb://NOTIFICATION
          perdicates:
            - Path=/api/v1/notification/**


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
